class Problem:
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,… By considering the terms in the Fibonacci sequence whose
    values do not exceed four million, find the sum of the even-valued terms.
    """

    def compute_answer(self) -> int:
        fib_generator = self._next_fibonacci()
        answer = 0
        while True:
            fibonacci_number = next(fib_generator)
            if fibonacci_number >= 4_000_000:
                break

            if fibonacci_number % 2 == 0:
                answer += fibonacci_number

        return answer

    def _next_fibonacci(self):
        number_1 = 0
        number_2 = 1

        while True:
            yield number_1 + number_2
            number_1, number_2 = number_2, number_1 + number_2
